### ISSUE TITLE
npm install faced error

### ISSUE THREAD

**Issue by PSepah** [npapp-dev/bpmn-angular-integration-examples#1]
I faced problem on npm install and i resolved it by changing the package.json as the following:
  "dependencies": {
    "@angular/animations": "^14.1.0",
    "@angular/common": "^14.1.0",
    "@angular/compiler": "^14.1.0",
    "@angular/core": "^14.1.0",
    "@angular/forms": "^14.1.0",
    "@angular/platform-browser": "^14.1.0",
    "@angular/platform-browser-dynamic": "^14.1.0",
    "@angular/router": "^14.1.0",
    "@bpmn-io/properties-panel": "^2.2.0",
    "bootstrap": "^5.2.0",
    "bpmn-js": "^11.5.0",
    "bpmn-js-properties-panel": "^1.26.0",
    "core-js": "^3.24.1",
    "rx": "^4.1.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "^0.11.8"
  },

**Comment by npapp-dev** [comment]
Thank you for reporting the issue.
