### ISSUE TITLE
Getting the error useId does not exist in preact/hooks

### ISSUE THREAD

**Issue by aravindc123** [npapp-dev/bpmn-angular-integration-examples#2]
./node_modules/@bpmn-io/diagram-js-ui/lib/index.js:3:0-183 - Error: export 'useId' (reexported as 'useId') was not found in 'preact/hooks' (possible exports: useCallback, useContext, useDebugValue, useEffect, useErrorBoundary, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState)

**Comment by aravindc123** [comment]
Hi, any idea why i am getting the above error ?

**Comment by npapp-dev** [comment]
Thank you for reporting the issue.
